### PR TITLE
add readme

### PR DESCRIPTION
**Pull request by quixoticquandary**

### CODE REVIEW

**Comment by ImJustStokedToBeHere** [comment]
If you plan on doing a lot of WPF work, I would recommend learning Blend as it’s specifically for UI design. It’s a much more robust tool


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by ImJustStokedToBeHere** [comment]
Every so often we should be rebasing our branches off of each others latest work. This is so that we don’t have a bunch of merge conflicts all of a sudden.

If you have stuff you don’t want to base over, you can stash your changes , then do the rebase, then you can restage your changes from the stash.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by quixoticquandary** [comment]
Good to know – I’m not sure to what extent I plan on doing WPF work, but this is good exposure to making a modern application.

**Comment by quixoticquandary** [comment]
This is true. I haven’t done anything worthy of making another pull request yet, but I will let you know if there’s something significant to rebase off of.

**Comment by ImJustStokedToBeHere** [comment]
Im gonna setup notifications so that when we commit the other gets notified.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Pull request merged**
